config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :groups, only: [:index, :show, :destroy] do
      resource :group_members, only: [:destroy]
      resources :group_posts, only: [:index, :show, :destroy]
    end
    get '/search', to: 'searches#search'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do
    root to: 'homes#top'
    devise_for :users
    get '/search', to: 'searches#search'
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :permits, only: [:create, :destroy]
      resource :group_members, only: [:create, :destroy]
      resources :group_posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    end
    
    get "groups/:id/permits" => "groups#permits", as: :permits
  end

  # ゲストログイン機能
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/group_post.rb
class GroupPost < ApplicationRecord
  has_one_attached :gp_image

  belongs_to :group_member
  has_many :users, through: :group_members, source: :user
  has_many :groups, through: :group_members, source: :groups

  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode

  def get_gp_image
    unless gp_image.attached?
      file_path = Rails.root.join('app/javascript/images/no-image-post.jpeg')
      gp_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    gp_image
  end

end

app/controllers/admin/group_posts_controller.rb
class Admin::GroupPostsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  
  def index
    @group = Group.find(params[:group_id])
    respond_to do |format|
      format.html do
        @group_posts = @group.group_posts.page(params[:page]).order(created_at: :desc)
      end
      format.json do
        @group_posts = @group.group_posts
      end
    end
  end

  def show
    @group_post = GroupPost.find(params[:id])
    @user = @group_post.group_member.user
  end

  def destroy
    group_post = GroupPost.find(params[:id])
    user = group_post.group_member.user
    group_post.destroy
    redirect_to admin_group_group_posts_path
  end

  private

  def group_post_params
    params.require(:group_post).permit(:title, :body, :gp_image, :address)
  end
end

app/views/admin/group_posts/_index.html.erb
<div class="row row-cols-2 row-cols-md-3 g-4">
  <% group_posts.each do |group_post| %>
    <div class="col mb-3">
      <div class="card bg-dark h-100">

        <%= link_to admin_group_group_post_path(group_post.group_member.group_id, group_post.id) do %>
          <%= image_tag group_post.get_gp_image, class: "img-fluid card-img-top" %>
        <% end %>

        <div class="card-body">
          <h4><%= group_post.title %></h4>
          <p><span><i class="fa-solid fa-location-dot"></i> <%= group_post.address %></span></p>
          <p><%= group_post.body.truncate(100) %></p>
          <div class="pb-3">
            <%= link_to "削除", admin_group_group_post_path(group_post.group_member.group_id, group_post), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-outline-primary" %>
          </div>
        </div>
        
      </div>
    </div>
  <% end %>
</div>

app/views/admin/group_posts/index.html.erb
<div class="text-center mb-3">
  <h2><%= link_to @group.name, admin_group_path(@group) %></h2>
  <h2>投稿一覧</h2>
</div>

<%= render 'index', group_posts: @group_posts %>

<div class="container pb-3">
  <div id="map"></div>
</div>

<div class="d-flex justify-content-center">
  <%= paginate @group_posts, theme: 'twitter-bootstrap-4' %>
</div>

<%= javascript_pack_tag 'map', 'data-turbolinks-track': 'reload' %>

app/views/admin/group_posts/show.html.erb
<%= render "layouts/notice", object: @group_post %>

<!-- 投稿詳細画面 -->
<div class="container px-sm-0">
  <div class="col-sm-12 col-lg-10 px-sm-0 mx-auto">

    <p><%= link_to "<< 投稿一覧へ戻る", admin_group_group_posts_path(@group_post.group_member.group.id) %></p>

    <div class="text-center">
      <h2><%= @group_post.title %></h2>
      <%= image_tag @group_post.get_gp_image, class: "col-12 px-0 my-3" %>
    </div>
    <p><span><i class="fa-solid fa-location-dot"></i> <%= @group_post.address %></span></p>
    <%= simple_format(@group_post.body, sanitize: true)%>

    <!-- 投稿ユーザー情報 -->
    <div class="mb-3">
      <%= link_to admin_user_path(@user) do %>
        <%= image_tag @user.get_profile_image, size: "75x75", class: "icon-img rounded-circle" %>
        <%= @user.name %>
      <% end %>
    </div>
    
    <p>投稿日：<%= @group_post.created_at.strftime('%Y/%m/%d') %></p>

    <!-- 削除ボタン -->
    <div class="pb-3">
      <%= link_to "削除", admin_group_group_post_path(@group_post.group_member.group_id, @group_post), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-outline-primary" %>
    </div>

  </div>
</div>