config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :groups, only: [:index, :show, :destroy] do
      resource :group_members, only: [:destroy]
      resources :group_posts, only: [:index, :show, :destroy]
    end
    get '/search', to: 'searches#search'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do
    root to: 'homes#top'
    devise_for :users
    get '/search', to: 'searches#search'
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :permits, only: [:create, :destroy]
      resource :group_members, only: [:create, :destroy]
      resources :group_posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    end
    
    get "groups/:id/permits" => "groups#permits", as: :permits
  end

  # ゲストログイン機能
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :group_members, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :groups, through: :group_members
  has_many :owner_groups, class_name: "Group", foreign_key: "owner_id", dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 200 }

  has_one_attached :profile_image

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/javascript/images/no-image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [200, 200]).processed
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).order(created_at: :desc)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_dashboards_path, notice: 'ユーザーを削除しました。'
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]
  before_action :is_matching_login_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to new_user_registration_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email, :introduction)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>
  <label for="inputName">名前</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%><br>
  <label for="inputEmail">メールアドレス</label>
  <%= f.text_field :email, autofocus: true, id:"inputEmail", placeholder:"メールアドレス"%><br>
  <label for="inputIntroduction">自己紹介</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介"%><br>
  <label for="inputImage">プロフィール画像</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>
  <%= f.submit "変更" %><br>
  <%= link_to "退会する", user_path(@user), method: :delete, "data-confirm" => "本当に削除しますか？" %>
<% end %>

app/views/users/show.html.erb
<!-- マイページ -->
<div>
  <%= flash[:notice] %>
</div>

<!-- ユーザーの詳細 -->
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image %><br>
  <p><%= @user.introduction %></p><br>
  <% if @user.email != "guest@example.com" && @user == current_user %>
    <p><%= link_to "ユーザー編集", edit_user_path(@user) %></p>
    <p><%= link_to "退会する", user_path(@user), method: :delete, "data-confirm" => "本当に退会しますか？" %></p>
  <% end %>
</div>

<!-- ユーザーの投稿一覧 -->
<% @posts.each do |post| %>
<div>
  <%= link_to post_path(post.id) do %>
    <!-- style: "object-fit: contain;" 縦横比を維持したままサイズ変更 -->
    <%= image_tag post.get_image, width: 240, height: 160, style: "object-fit: contain;" %>
  <% end %>
  <p><b><%= post.title %></b></p>
  <p>本文：<%= post.body %></p>
  <p>ユーザーネーム：<%= post.user.name %></p>
  <p><%= link_to "#{post.comments.count} コメント", post_path(post.id) %></p>
  <% if @user == current_user %>
    <p><%= link_to "編集", edit_post_path(post) %></p>
    <p><%= link_to "削除", post_path(post), method: :delete, "data-confirm" => "本当に削除しますか？" %></p>
  <% end %>
</div>
<% end %>