config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :groups, only: [:index, :show, :destroy] do
      resource :group_members, only: [:destroy]
      resources :group_posts, only: [:index, :show, :destroy]
    end
    get '/search', to: 'searches#search'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do
    root to: 'homes#top'
    devise_for :users
    get '/search', to: 'searches#search'
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :permits, only: [:create, :destroy]
      resource :group_members, only: [:create, :destroy]
      resources :group_posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    end
    
    get "groups/:id/permits" => "groups#permits", as: :permits
  end

  # ゲストログイン機能
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :group_image
  belongs_to :owner, class_name: 'User', foreign_key: "owner_id" 

  has_many :group_members, dependent: :destroy
  has_many :users, through: :group_members, source: :user
  has_many :group_posts, through: :group_members, source: :group_posts
  has_many :permits, dependent: :destroy
  
  validates :name, presence: true, length: { maximum: 50 }

  def get_group_image
    unless group_image.attached?
      file_path = Rails.root.join('app/javascript/images/no-image.jpeg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    group_image
  end

  def is_owned_by?(user)
    owner.id == user.id
  end
  
  def includesUser?(user)
    group_members.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Group.where(name: content)
    elsif method == 'forward'
      Group.where('name LIKE ?', content+'%')
    elsif method == 'backward'
      Group.where('name LIKE ?', '%'+content)
    else
      Group.where('name LIKE ?', '%'+content+'%')
    end
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @post = Post.new
    @groups = Group.all.order(created_at: :desc)
  end

  def show
    @post = Post.new
    @group = Group.find(params[:id])
    @users = @group.users
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to admin_groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

end

app/views/admin/groups/_index.html.erb
<div class="container">
  <div class="col-sm-12 col-md-10 px-sm-0 mx-auto">
    <table class="table table-hover bg-light">

      <thead class="thead-dark">
        <tr>
          <th></th>
          <th>グループ名</th>
          <th>オーナー</th>
          <th>メンバー数</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <% groups.each do |group| %>
        <tbody>
          <tr>
            <td><%= image_tag group.get_group_image, size: "50x50", class: "icon-img shadow-sm" %></td>
            <td><%= link_to group.name, admin_group_path(group), class: "group_#{group.id}" %></td>
            <td><%= group.owner.name %></td>
            <td><%= group.group_members.count %></td>
            <td><%= link_to "削除", admin_group_path(group), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-secondary" %></td>
          </tr>
        </tbody>
      <% end %>
      
    </table> 
  </div>
</div>

app/views/admin/groups/index.html.erb
<h2 class="text-center pb-2">グループ一覧</h2>
<%= render 'index', groups: @groups %>

app/views/admin/groups/show.html.erb
<div class="container px-sm-0">
  <div class="col-sm-12 col-lg-10 px-sm-0 mx-auto">

    <p><%= link_to "<< グループ一覧へ戻る", admin_groups_path %></p>

    <div class="text-center pb-3">
      <h2><%= @group.name %></h2>
      <%= image_tag @group.get_group_image, size: "200x200", class: "icon-img mt-2 mb-3" %><br>
      <%= link_to "削除", admin_group_path(@group), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-outline-primary" %>
    </div>

    <div class="row mt-3">
      <div class="col-11 col-md-10 mx-auto pb-3">
        <%= simple_format(@group.introduction, sanitize: true)%>
        オーナー：
        <%= link_to admin_user_path(@group.owner) do %>
          <%= image_tag @group.owner.get_profile_image, size: "75x75", class: "icon-img rounded-circle" %>
          <%= @group.owner.name %>
        <% end %>
        <div class="mt-4">
          <%= link_to "グループ投稿一覧", admin_group_group_posts_path(@group) %>
        </div>
      </div>
    </div>

    <h3 class="text-center mt-5">メンバー一覧</h3>
    <div class="row mt-3">
      <div class="col-11 col-md-10 mx-auto">
        <% @users.each do |user| %>
          <table class="pb-3">
            <tr>
              <td class="p-2"><%= image_tag user.get_profile_image, size: "75x75", class: "icon-img rounded-circle" %></td>
              <td class="p-2"><%= link_to user.name, admin_user_path(user) %></td>
              <% if @group.is_owned_by?(user) %>
                <td class="p-2">【オーナー】</td>
              <% else %>
                <td class="p-2"><%= link_to "グループ退会", admin_group_group_members_path(@group, user_id: user.id), method: :delete, "data-confirm" => "グループを退会させますか？", class: "btn btn-sm btn-secondary" %></td>
              <% end %>
            </tr>
          </table>
        <% end %>
      </div>
    </div>

  </div> 
</div> 