config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :groups, only: [:index, :show, :destroy] do
      resource :group_members, only: [:destroy]
      resources :group_posts, only: [:index, :show, :destroy]
    end
    get '/search', to: 'searches#search'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do
    root to: 'homes#top'
    devise_for :users
    get '/search', to: 'searches#search'
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :permits, only: [:create, :destroy]
      resource :group_members, only: [:create, :destroy]
      resources :group_posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    end
    
    get "groups/:id/permits" => "groups#permits", as: :permits
  end

  # ゲストログイン機能
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning" role="alert">
    <h5>
      <i class="fa-solid fa-triangle-exclamation"></i> 
      <%= object.errors.count %>件のエラーが発生しました
    </h5>
    <ul class="mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
  <div class="alert alert-primary" role="alert">
    <i class="fa-solid fa-circle-check"></i>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning" role="alert">
    <i class="fa-solid fa-triangle-exclamation"></i> 
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
  <head>
    <title>管理者画面 - ヨルポス</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/af13550893.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-light bg-light shadow">
        <div class="container">
          <div class="navbar-brand">ヨルポス - 管理者画面</div>

            <% if admin_signed_in? %>
              <!-- メニュー（ハンバーガーメニュー）-->
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <!-- メニューリスト -->
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <div class="search_form mt-2">
                    <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
                      <input type="text" name="content" id="content" placeholder="キーワードを入力" class="col-4 form-control form-control-sm">
                      <select name="model" id="model" class="btn btn-sm btn-secondary">
                        <option value="user">ユーザー</option>
                        <option value="post">投稿</option>
                        <option value="group">グループ</option>
                      </select>
                      <select name="method" id="method" class="btn btn-sm btn-secondary">
                        <option value="perfect">完全一致</option>
                        <option value="forward">前方一致</option>
                        <option value="backward">後方一致</option>
                        <option value="partial">部分一致</option>
                      </select>
                      <%= f.button class: "btn btn-secondary btn-sm" do %>
                        <i class="fa-solid fa-magnifying-glass"></i>
                      <% end %>
                    <% end %>
                  </div>

                  <li>
                    <%= link_to admin_posts_path, class: "nav-link" do %>
                      <i></i> 投稿一覧
                    <% end %>
                  </li>
                  <li>
                    <%= link_to admin_dashboards_path, class: "nav-link" do %>
                      <i></i> ユーザー一覧
                    <% end %>
                  </li>
                  <li>
                    <%= link_to admin_groups_path, class: "nav-link" do %>
                    <i></i> グループ一覧
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %>
                      <i></i> ログアウト
                    <% end %>
                  </li>
                </ul>
              </div>
            <% end %>
            
          </div>
        </div>
      </nav>
    </header>


    <main class="mb-auto p-4">
      <%= yield %>

      <span id="back">
        <a href="#">
          <i class="fa-solid fa-circle-chevron-up fa-3x"></i>
        </a>
      </span>
    </main>

    <div class="bg01">
      <%= image_tag 'bg01.png', class: 'img-fluid' %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
    <%= javascript_pack_tag 'scroll_top' %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>ヨルポス</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/af13550893.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-dark bg-dark shadow">
        <div class="container">

          <!--トップページへのリンク-->
          <%= link_to "ヨルポス", root_path, class: "navbar-brand text-center mr-0" %>

          <!--メニュー（ハンバーガーメニュー）-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <!--メニューリスト-->
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <!--ログイン時-->
                <div class="search_form mt-2">
                  <%= form_with url: search_path, method: :get, local: true do |f| %>
                    <input type="text" name="content" id="content" placeholder="キーワードを入力" class="col-4 form-control form-control-sm">
                    <select name="model" id="model" class="btn btn-sm btn-secondary">
                      <option value="user">ユーザー</option>
                      <option value="post">投稿</option>
                      <option value="group">グループ</option>
                    </select>
                    <select name="method" id="method" class="btn btn-sm btn-secondary">
                      <option value="perfect">完全一致</option>
                      <option value="forward">前方一致</option>
                      <option value="backward">後方一致</option>
                      <option value="partial">部分一致</option>
                    </select>
                    <%= f.button class: "btn btn-secondary btn-sm" do %>
                      <i class="fa-solid fa-magnifying-glass"></i>
                    <% end %>
                  <% end %>
                </div>

                <li>
                  <%= link_to user_path(current_user.id), class: "nav-link" do %>
                    <i></i> マイページ
                  <% end %>
                </li>
                <li>
                  <%= link_to new_post_path, class: "nav-link" do %>
                    <i></i> 新規投稿
                  <% end %>
                </li>
                <li>
                  <%= link_to posts_path, class: "nav-link" do %>
                    <i></i> 投稿一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to groups_path, class: "nav-link" do %>
                    <i></i> グループ一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                    <i></i> ログアウト
                  <% end %>
                </li>
              <% else %>
                <!--ログイン前-->
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link" do %>
                    <i></i> 新規登録
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link" do %>
                    <i></i> ログイン
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>

        </div>
      </nav>
    </header>

    <main class="mb-auto p-4">
      <%= yield %>

      <span id="back">
        <a href="#">
          <i class="fa-solid fa-circle-chevron-up fa-3x"></i>
        </a>
      </span>
    </main>

    <div class="bg01">
      <%= image_tag 'bg01.png', class: 'img-fluid' %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
    <%= javascript_pack_tag 'scroll_top' %>

  </body>
</html>